export declare const name: string;
export declare const version: string;
export declare const description: string;
export declare const main: string;
export declare const types: string;
export declare const scripts: {
    "build": string;
    "build:dist": string;
    "build:dist-min": string;
    "build:es5": string;
    "build:release": string;
    "clean": string;
    "docs": string;
    "lint": string;
    "release": string;
    "status": string;
    "test": string;
    "test:unit": string;
    "test:integration": string;
};
export declare const contributors: string[];
export declare const license: string;
export declare const keywords: string[];
export declare const dependencies: {
    "@types/events": string;
    "@types/node": string;
    "events": string;
};
export declare const devDependencies: {
    "@types/mocha": string;
    "@types/sinon": string;
    "browserify": string;
    "coverage": string;
    "is-docker": string;
    "karma": string;
    "karma-chrome-launcher": string;
    "karma-firefox-launcher": string;
    "karma-mocha": string;
    "karma-spec-reporter": string;
    "karma-typescript": string;
    "mocha": string;
    "npm-run-all": string;
    "nyc": string;
    "twilio-release-tool": string;
    "sinon": string;
    "travis-multirunner": string;
    "ts-node": string;
    "tsify": string;
    "tslint": string;
    "twilio": string;
    "typedoc": string;
    "typedoc-plugin-as-member-of": string;
    "typedoc-plugin-external-module-name": string;
    "typedoc-plugin-internal-external": string;
    "typedoc-twilio-theme": string;
    "typescript": string;
    "vinyl-fs": string;
    "vinyl-source-stream": string;
};
