declare const _exports: {
    "name": string;
    "version": string;
    "description": string;
    "main": string;
    "types": string;
    "scripts": {
        "build": string;
        "build:dist": string;
        "build:dist-min": string;
        "build:es5": string;
        "build:release": string;
        "clean": string;
        "docs": string;
        "lint": string;
        "release": string;
        "status": string;
        "test": string;
        "test:unit": string;
        "test:integration": string;
    };
    "contributors": string[];
    "license": string;
    "keywords": string[];
    "private": boolean;
    "dependencies": {
        "@types/events": string;
        "@types/node": string;
        "events": string;
    };
    "devDependencies": {
        "@types/mocha": string;
        "@types/sinon": string;
        "browserify": string;
        "coverage": string;
        "is-docker": string;
        "karma": string;
        "karma-chrome-launcher": string;
        "karma-firefox-launcher": string;
        "karma-mocha": string;
        "karma-spec-reporter": string;
        "karma-typescript": string;
        "mocha": string;
        "npm-run-all": string;
        "nyc": string;
        "release-tool": string;
        "sinon": string;
        "travis-multirunner": string;
        "ts-node": string;
        "tsify": string;
        "tslint": string;
        "twilio": string;
        "typedoc": string;
        "typedoc-plugin-as-member-of": string;
        "typedoc-plugin-external-module-name": string;
        "typedoc-plugin-internal-external": string;
        "typedoc-twilio-theme": string;
        "typescript": string;
        "vinyl-fs": string;
        "vinyl-source-stream": string;
    };
};
export = _exports;
